# Generated by Django 5.2.8 on 2025-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=75)),
                ('first_name', models.CharField(max_length=75)),
                ('middle_name', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=75)),
                ('contact', models.CharField(max_length=75)),
                ('grade', models.CharField(max_length=100)),
                ('school', models.TextField()),
                ('address', models.TextField()),
                ('is_four', models.BooleanField(default=False)),
                ('gwa', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DataEntryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(verbose_name='open_date')),
                ('close_date', models.DateField(verbose_name='close_date')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_number', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
