# Generated by Django 5.2.8 on 2025-12-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='scholar_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
