# Generated by Django 5.2.8 on 2025-12-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0002_applicants_scholar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='address',
        ),
        migrations.AddField(
            model_name='applicants',
            name='brgy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='province',
            field=models.CharField(default='Camarines Norte', max_length=250),
        ),
        migrations.AddField(
            model_name='applicants',
            name='purok',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
