# Generated by Django 5.2.8 on 2025-12-21 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0003_remove_applicants_address_applicants_brgy_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='brgy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.barangay'),
        ),
    ]
