# Generated by Django 5.2.8 on 2025-12-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0004_alter_applicants_brgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='name_ext',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='province',
            field=models.CharField(default='Labo Camarines Norte', max_length=250),
        ),
    ]
