# Generated by Django 5.2.8 on 2025-12-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0005_applicants_name_ext_alter_applicants_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='guardian_first_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='guardian_last_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='guardian_middle_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='guardian_name_ext',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='email',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
