# Generated by Django 5.2.8 on 2025-12-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0006_applicants_guardian_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
