# Generated by Django 5.2.8 on 2025-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0007_applicants_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
