# Generated by Django 5.2.8 on 2026-01-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0008_applicants_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='date_approved',
            field=models.DateField(editable=False, null=True),
        ),
    ]
