# Generated by Django 5.2.8 on 2026-01-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0009_applicants_date_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='date_approved',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
