# Generated by Django 5.2.8 on 2026-01-08 02:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0010_alter_applicants_date_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
