# Generated by Django 5.2.8 on 2026-01-08 02:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0011_alter_applicants_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
