# Generated by Django 5.2.8 on 2026-01-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_assistance', '0012_applicants_uid_alter_applicants_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='level',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
