# Generated by Django 5.2.8 on 2025-12-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='type_of_goods',
            new_name='type_of_good',
        ),
    ]
