# Generated by Django 5.2.8 on 2025-12-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_is_deleted_employee_stat'),
        ('procurement', '0003_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(max_length=250)),
                ('date_of_purchase', models.DateField(null=True)),
                ('approved_budget', models.BigIntegerField()),
                ('charging', models.TextField(null=True)),
                ('min_of_meeting', models.TextField(null=True)),
                ('bac_resolution', models.CharField(max_length=250)),
                ('proof_of_service', models.TextField(null=True)),
                ('rfqs', models.CharField(max_length=250)),
                ('winning_supplier', models.CharField(max_length=250)),
                ('recommending_award', models.TextField(null=True)),
                ('philgeps', models.TextField(null=True)),
                ('po_number', models.CharField(max_length=250)),
                ('posting_of_award', models.DateField()),
                ('philgeps_reg_no', models.CharField(max_length=250)),
                ('mayors_no', models.CharField(max_length=250)),
                ('date_delivery', models.DateField(null=True)),
                ('date_received', models.DateField(null=True)),
                ('date_check', models.DateField(null=True)),
                ('checks', models.CharField(max_length=250, null=True)),
                ('remarks', models.TextField(null=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('mode_of_procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.mode')),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('type_of_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.type_of_good')),
            ],
        ),
    ]
