# Generated by Django 5.2.8 on 2025-12-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_is_deleted_employee_stat'),
        ('procurement', '0004_procument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procument',
            new_name='Procurement',
        ),
    ]
