# Generated by Django 5.2.8 on 2025-12-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_rename_procument_procurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='rfqs',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
