# Generated by Django 5.2.8 on 2025-12-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_is_deleted_employee_stat'),
        ('procurement', '0006_alter_procurement_rfqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='approved_budget',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='bac_resolution',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='mayors_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='mode_of_procurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.mode'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='person_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='philgeps_reg_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='po_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='posting_of_award',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='purchase_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='type_of_good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.type_of_good'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='winning_supplier',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
