# Generated by Django 5.2.8 on 2025-12-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_alter_procurement_approved_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
