# Generated by Django 5.2.8 on 2025-12-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_procurement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='status',
        ),
        migrations.AddField(
            model_name='procurement',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
