# Generated by Django 5.2.8 on 2025-11-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.venues'),
        ),
    ]
