# Generated by Django 5.2.8 on 2025-11-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_events_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='venue',
            field=models.TextField(),
        ),
    ]
