# Generated by Django 5.2.8 on 2025-11-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_venues_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.venues'),
        ),
    ]
