# Generated by Django 5.2.8 on 2025-11-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('types', models.CharField(max_length=50)),
                ('msg', models.TextField()),
            ],
        ),
    ]
