# Generated by Django 5.2.8 on 2025-12-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(max_length=250)),
                ('first_name', models.TextField(max_length=250)),
                ('middle_name', models.TextField(max_length=200, null=True)),
                ('name_ext', models.TextField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=250)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Annulled', 'Annulled')], max_length=250)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.TextField()),
                ('address', models.TextField()),
                ('tin', models.CharField(blank=True, max_length=15, null=True)),
                ('gsis', models.CharField(blank=True, max_length=20, null=True)),
                ('pagibig', models.CharField(blank=True, max_length=20, null=True)),
                ('philhealth', models.CharField(blank=True, max_length=20, null=True)),
                ('sss', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('employment_status', models.CharField(choices=[('Regular', 'Regular Permanent'), ('Casual', 'Casual'), ('Coterminous', 'Co-terminous'), ('Job Order', 'Job Order (JO)'), ('Contract of Service', 'Contract of Service (COS)'), ('Elective', 'Elective Official'), ('Temporary', 'Temporary')], default='Casual', max_length=20)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('date_regularized', models.DateField(blank=True, null=True)),
                ('date_separation', models.DateField(blank=True, null=True)),
                ('has_eligibility', models.BooleanField(default=False)),
                ('eligibility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_of_examination', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('salary_grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
