# Generated by Django 5.2.8 on 2025-12-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_department_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name_ext',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
