# Generated by Django 5.2.8 on 2025-12-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_name_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Employee photo (optional)', null=True, upload_to='employees/profile/'),
        ),
    ]
