# Generated by Django 5.2.8 on 2025-12-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_examination',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_regularized',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_separation',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
