# Generated by Django 5.2.8 on 2025-12-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_is_deleted_alter_employee_date_hired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='employee',
            name='stat',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
