# Generated by Django 5.2.7 on 2025-12-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_is_deleted_employee_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='user', max_length=254),
        ),
    ]
